// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGrFv7sNrUbP-epeG-vOhMH5R4FQ7Uo0',
    appId: '1:213105718117:web:ff8b18d69fe5d00ee8a78c',
    messagingSenderId: '213105718117',
    projectId: 'character-app-67b2b',
    authDomain: 'character-app-67b2b.firebaseapp.com',
    storageBucket: 'character-app-67b2b.firebasestorage.app',
    measurementId: 'G-S234VXYLC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM8on4l212Il6sW-JM846HJsIebtuMnow',
    appId: '1:213105718117:android:670635cc9adac375e8a78c',
    messagingSenderId: '213105718117',
    projectId: 'character-app-67b2b',
    storageBucket: 'character-app-67b2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALsc-GtUxyC0qAIVZpwHD8IodH9swwrfk',
    appId: '1:213105718117:ios:ddd93b85045b0ff0e8a78c',
    messagingSenderId: '213105718117',
    projectId: 'character-app-67b2b',
    storageBucket: 'character-app-67b2b.firebasestorage.app',
    iosBundleId: 'com.azizdev.characterApp',
  );
}
